version: "2.34"

services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./MinIO/data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    restart: unless-stopped

  mongo2:
    image: mongo:8.0.9
    container_name: mongo2
    ports:
      - "27018:27017"
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0", "--bind_ip_all"]
    restart: unless-stopped

  mongo3:
    image: mongo:8.0.9
    container_name: mongo3
    ports:
      - "27019:27017"
    networks:
      - mongo-cluster
    command: ["--replSet", "rs0", "--bind_ip_all"]
    restart: unless-stopped

  webapp:
    build: ./WebApp
    container_name: webapp
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development 
      # MINIO_ENDPOINT: 192.168.3.69:9000
      # # MINIO_ACCESS_KEY: CLR1bkuA5m9VT5DQtBms
      # # MINIO_SECRET_KEY: yM1yfUIbTxeFcdXzx8gCf6xFHNhWbWpJ1lPVax8w
    depends_on:
      - minio
    restart: unless-stopped

networks:
  mongo-cluster:
    driver: bridge